### ISSUE TITLE
cannot install on debian buster

### ISSUE THREAD

**Issue by mailinglists35** [saljam/webwormhole#103]
using   golang-1.15-go golang-1.15-src golang-go golang-src
on debian 10 (buster)
````
root@server:/usr/local/src# git clone https://github.com/saljam/webwormhole.git
Cloning into 'webwormhole'...
remote: Enumerating objects: 1348, done.
remote: Counting objects: 100% (189/189), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 1348 (delta 171), reused 148 (delta 148), pack-reused 1159
Receiving objects: 100% (1348/1348), 487.61 KiB | 3.36 MiB/s, done.
Resolving deltas: 100% (788/788), done.
root@server:/usr/local/src# cd webwormhole/
root@server:/usr/local/src/webwormhole# go install webwormhole.io/cmd/ww@latest
package webwormhole.io/cmd/ww@latest: can only use path@version syntax with 'go get'
````

**Comment by saljam** [comment]
try `go install ./cmd/ww` in the root directory?

i think the `@latest` syntax only got introduced with go 1.16. i should probably add a note about this in readme. go modules pre-1.16 is just a mess.

**Comment by mailinglists35** [comment]
yup, running without `@latest` works, as well as `go install ./cmd/ww`
thank you! :)

**Comment by mailinglists35** [comment]
by the way, debian stable release version is now 11 (codename bullseye) and also includes go 1.15

**Comment by saljam** [comment]
literally the first thing i checked too. :)

that's unfortunate since 1.15 is officially unsupported by the go team *two days* after bullseye was release. they only support the latest two major releases. https://golang.org/doc/devel/release#policy

ah well.
