### ISSUE TITLE
figure out a convenient way to run the web ui locally

### ISSUE THREAD

**Issue by saljam** [saljam/webwormhole#13]
While the trust model does not include the signalling server, it does include wherever the web interface came from. If our "official" instance ever gets compromised it can e.g. inject malicious javascript and we don't want that. We we need a way to run "known trusted" versions of the web UI.

You can't just save the html/js files to disk and open that. Wasm and JS modules can't be loaded from file:// URLs.

Maybe we can encode the wasm as base64 and stick that in index.html?

Maybe embedding the webui in the signalling server is enough? We can give it an option to choose whether to use the local instance for signalling or the default one.

**Comment by dfabulich** [comment]
I suggest serving an Electron app. That's what Signal uses; it's pretty nice.

**Comment by saljam** [comment]
great suggestions. a browser extension sounds like an option too.

**Comment by saljam** [comment]
https://github.com/WICG/webpackage

**Comment by saljam** [comment]
It occurs to me that if we use absolute paths and SRI for all the subresources (js, css, wasm) then saving index.html and opening it with a file:// url should still work. This can be a simple alternative for people who want reassurance that no unexpected updates to the code deployed on webwormhole.io have happened.

That said, this is not something I'd recommend doing until the signalling protocol is more stable.

**Comment by saljam** [comment]
https://github.com/saljam/webwormhole/commit/f634f3a5d23e310fb7643f1a31fb4858bc07bf68

submitted to chrome and firefox, awaiting review.

**Comment by saljam** [comment]
on chrome: https://chrome.google.com/webstore/detail/webwormhole/jhombkhjanncdalcbcahinpjoacaiidn
on firefox: https://addons.mozilla.org/en-US/firefox/addon/webwormhole

it's not listed yet on either store, but if anyone wants to poke at them feel free!

**Comment by saljam** [comment]
the extensions seem to work well enough to close this.

at some point a mobile app would also be nice to have. even a crappy webview one as long as it can implement "share with" feature. but i'll save that can of worms for another day.
