### ISSUE TITLE
Tell users about the infrastructure

### ISSUE THREAD

**Issue by szepeviktor** [saljam/webwormhole#25]
Please consider writing about

- stun.l.google.com
- and your DO server wrmhl.link

as they are involved in the connection.

**Comment by saljam** [comment]
Sure. Maybe a "how it works" pop up diagram, showing the peers, the STUN servers, and the signalling server, and what data is transferred between each.

**Comment by szepeviktor** [comment]
Yes. Thank you.

**Comment by saljam** [comment]
FWIW: we run our own ICE server and no longer use google's.

**Comment by saljam** [comment]
it's no fancy popups or diagrams, but i've added more words to the readme. i think the last few paragraphs give a better description of the infrastructure and trust model, so i'll close this now.

if you think it's still missing important information let me know.

**Comment by szepeviktor** [comment]
Thank you.
