### ISSUE TITLE
tried the hackernews demo

### ISSUE THREAD

**Issue by andrewarrow** [saljam/webwormhole#27]
![bug1](https://user-images.githubusercontent.com/127054/80661985-09cc9380-8a45-11ea-8278-c1f3c93c33f8.png)

![bug2](https://user-images.githubusercontent.com/127054/80661991-0cc78400-8a45-11ea-986b-5540c78986c2.png)

Any idea why browser gets this error?

**Comment by andrewarrow** [comment]
<img width="707" alt="bug3" src="https://user-images.githubusercontent.com/127054/80662123-57e19700-8a45-11ea-95b1-2d46f43908e4.png">

I was running this on another machine

**Comment by saljam** [comment]
Does this happen occasionally or every time?

404 means the "slot" the peers use to authenticate each other was no longer there on the signalling server. It either timed out, or the command line client for some reason got disconnected. The command line client should probably be better at showing when this happens.

**Comment by saljam** [comment]
I just noticed the `%20` in the first set of log lines - I think it was trying to join the wrong code. We should definitely sanitise the codes to avoid that. I'll make another issue to track that. #46

I'll close this but feel free to post a comment if you're still having trouble connecting.
