### ISSUE TITLE
ios 12 does not support blob urls

### ISSUE THREAD

**Issue by hantusk** [saljam/webwormhole#30]
Tried pushing a file through the wormhole, and the file was listed at both ends - however, I could not click(touch) the file from an iPhone 8 in the web interface, so I couldn't download the file.

**Comment by saljam** [comment]
Do you have a screenshot of what happened on the iPhone? Did it show the filename in the middle of the screen?

If it worked correctly the download starts automatically and is handled by safari's download dialog.

**Comment by hantusk** [comment]
Using Google Chrome on the iPhone forgot to mention. Filename is being shown in the middle of the screen, but nothing happens, and can't click it.
![856ADE41-C58A-40C3-BBDE-AD5B6594C6D1](https://user-images.githubusercontent.com/7280549/80798207-20d5c780-8ba4-11ea-8ed0-3f104205c9c5.PNG)

**Comment by saljam** [comment]
thanks! i can reproduce this on ios chrome. the download should trigger automatically but it doesn't.

i'll change it so the file name is also a link. that would be a reliable fallback in cases where this happens.

**Comment by saljam** [comment]
I was wrong, it's not about automatically triggering downloads. apparently ios chrome doesn't like blob urls.

There's a few workarounds here: https://stackoverflow.com/questions/24485077/how-to-open-blob-url-on-chrome-ios

**Comment by saljam** [comment]
Digging around this it seems an iOS 12 issue and it affects safari too. I have a phone at 12.4.5 that has this, and a phone at 13.2.3 that doesn't.
