### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by trisquared** [saljam/webwormhole#32]
It appears that webwormhole does not work with internet explorer. If you navigate to webwormhole.io in IE you do not get the "new wormhole option" it just says "loading" on the button. If you enter a code, the button also does not allow you to submit.

**Comment by saljam** [comment]
It seems like IE supports neither WebRTC nor WebAssembly, both of which are requirements for this project I'm afraid.

https://caniuse.com/#feat=rtcpeerconnection
https://caniuse.com/#feat=wasm

Edge does have them both, but I've not tested it. I'll leave this issue open until someone confirms it.

**Comment by alexon1234** [comment]
In edge is working fine 

Edge version 81.0.416.68 (Official build) (64-bit)

**Comment by saljam** [comment]
Thanks for confirming @alexon1234!

It seems unlikely IE will add support for WebRTC or WebAssembly, given how discontinued it is. At least it should get a slightly less confusing message now.
