### ISSUE TITLE
Doesn't work on android 6

### ISSUE THREAD

**Issue by nathgit** [saljam/webwormhole#34]
I've tried with 3 different browsers on android 6 marshmallow. I tried with Chrome, link bubble, & Hermit. The button just says loading & The text box doesn't do anything when I type in a code.

**Comment by trisquared** [comment]
What browser versions?

**Comment by nathgit** [comment]
chrome:55.0.2883.91
link bubble:1.9.58
hermit:15.5.2

Hermit was updated recently. The other 2 haven't been updated recently.

**Comment by saljam** [comment]
It seems like Chrome 55 does not support WebAssembly, which is a requirement for this project.

https://caniuse.com/#feat=wasm

I've not heard of the other two browsers and they're not on caniuse.com. I'm currently writing JS feature detection so soon the app will show a nicer error message if any of the browser features it needs are missing.

**Comment by saljam** [comment]
@nathgit going to close this with the assumption these browsers lack WebAssembly or WebRTC. We kinda need those, sorry!

The current version should display a more helpful message if any of these features are missing. Please reopen if you don't get that message.

**Comment by nathgit** [comment]
I believe link bubble was removed from the play store because a change in android's API. Hermit is here: https://play.google.com/store/apps/details?id=com.chimbori.hermitcrab
