### ISSUE TITLE
docker-compose.yml?

### ISSUE THREAD

**Issue by zub0r** [saljam/webwormhole#35]
Is it possible to run this with a simple docker-compose.yml as a microservice? 
Or is there any reason why the project is tightly coupled with linuxkit world?
Thx

**Comment by saljam** [comment]
That should be fine. The Dockerfile is completely independent from the LinuxKit stuff.

In the repository root, running:
```
$ docker build -f werkzeuge/Dockerfile -t webwormhole .
```
should produce a docker image called webwormhole that runs the server by default.

```
$ docker run --rm -it webwormhole -h
run the webwormhole signalling server

usage: /bin/ww server

flags:
  -hosts string
    	comma separated list of hosts for which to request let's encrypt certs (default ":https")
  -http string
    	http listen address (default ":http")
  -https string
    	https listen address (default ":https")
  -secrets string
    	path to put let's encrypt cache (default "/root/keys")
  -ui string
    	path to the web interface files (default "/lib/webwormhole/web")
```

If you want to run other subcommands, override the entrypoint.

```
     docker run --rm -it --entrypoint=ww webwormhole pipe
9-village-december
...
```

The linuxkit stuff uses this docker image, not the other way around. It's just there to make my deployments easier.

I'll close this but feel free to reopen if there's anything we can do to make using the docker image easier!

**Comment by zub0r** [comment]
Thank you for explaining - I was under impression that linuxkit is necessary along with certificate generation.
This way I was able to run it locally with 
`docker run --rm -it --network=host webwormhole  -http='localhost:8000' -https=""`
to disable acme cert fetching.

**Comment by saljam** [comment]
glad to hear. i should probably document the `-https=""` trick more clearly.
