### ISSUE TITLE
Pasting a new fragment does not initiate a new session

### ISSUE THREAD

**Issue by lxgr** [saljam/webwormhole#50]
When pasting a URL with a new fragment to an existing browser window, state is not updated to take the new fragment into account. A reload is required to initiate the connection.

**Comment by saljam** [comment]
[onhashchange](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange) seems to be the event we should watch

**Comment by lxgr** [comment]
I think I have a fix for this! Let me quickly open a PR
