### ISSUE TITLE
Should a closed websocket cancel a connetion attempt?

### ISSUE THREAD

**Issue by lxgr** [saljam/webwormhole#52]
When trying to join a portal that's in the wrong state (stale/already used up link), the UI just hangs instead of offering to start a new portal.

Could the signalling server maybe send a clean error (instead of just dropping the websocket)? Or would it be fine to just go back to "disconnected" on a dropped websocket for any reason?

**Comment by lxgr** [comment]
Hm, just saw the "no such slot" error message, but somehow this does not end up at the browser. Chrome just shows an abnormal closure (code 1006, no message).

**Comment by saljam** [comment]
interesting. "no such slot" message works in firefox, but you're right it's broken in chrome.

worth noting: the message uses non-standard websocket code (404!) but it needs to be in the 4000–4999 range according to [mdn](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent). i've been meaning to fix that, i'll check if that's the reason.

**Comment by lxgr** [comment]
That's what I tried too – no success unfortunately :(

**Comment by lxgr** [comment]
It seems like Chrome is more picky about Websockets than Firefox and Safari (and the server is hitting that behavior): https://stackoverflow.com/questions/19304157/getting-the-reason-why-websockets-closed-with-close-code-1006

**Comment by saljam** [comment]
i think this is this: gorilla/websocket#539

fix incoming

**Comment by saljam** [comment]
<img width="711" alt="sc" src="https://user-images.githubusercontent.com/751023/81239067-c2f51580-8fd1-11ea-85a4-9268f744de8e.png">

explicitly closing the connections seems to do the job.
