### ISSUE TITLE
Connection problem when trying to connect via mobile network

### ISSUE THREAD

**Issue by jankatins** [saljam/webwormhole#56]
I've a connection problem but only when on different networks: Tried between my laptop (Debian linux, chrome) and my mobile (Android, Chrome): when I am connected with both devices to the same wifi, it works, but not when I set the mobile to LTE (O2 German) only. Happens both direction.

Interestingly, I also tried to deploy webwormhole on a local NAS which is accessible via a CNAME + port forwarding on the router + a reverse proxy (traefik) from the outside, and there it's the same (both on wifi: works; mobile outside: broken in both directions). The only thing I see on the log is 

```
webwormhole             | 2020/05/10 02:33:07 4 book
webwormhole             | 2020/05/10 02:33:33 4 visit
webwormhole             | 2020/05/10 02:33:33 4 rendezvous
```

When I try https://test.webrtc.org/ while on the mobile network, then this gives me an error in the connectivity part:

```
Reflexive connectivity

[ INFO ] Gathered candidate of Type: srflx Protocol: udp Address: 46.114.39.xx
[ INFO ] Gathered candidate of Type: srflx Protocol: udp Address: 46.114.39.xx
[ WARN ] Could not connect using reflexive candidates, likely due to the network environment/configuration.
``` 
(it's fine on both devices when connected via wifi)

**Comment by saljam** [comment]
Thanks for reporting. (And testing on https://test.webrtc.org/ first!)

It seems like the signalling part is working fine for you (on both webwormhole.io and your deployment) despite the minimal logging. I'm guessing the LTE provider is running CGNAT and the peers having trouble negotiating a direct connection through it.

It's my understanding that in situations like this there's only two things we can do:
- Ask browsers for media permissions (ew!) so they use IPv6. (No idea why they do this but they do.)
- Run a fallback relay server.

I'm considering the latter with the spare capacity the signalling server has. I filed #57 to track that.

PS there's now more logging in the browser console (cmd/ctrl+alt+i).

**Comment by jankatins** [comment]
Didn't know about cgnat, but i have a 10.122.1.x ip, so seems to be the case.

Huih, i looked in such relay server, sounded scary to deploy to get a completely private wormhole :-\ wouldn't it be easier to fall back to a magic wormhole like server?

**Comment by saljam** [comment]
In WebRTC, TURN servers move encrypted traffic. So even if relayed, it's still end-to-end encrypted DTLS. It's actually quite similar to magic-wormhole.
