### ISSUE TITLE
Possible to queue up files before establishing a connection?

### ISSUE THREAD

**Issue by increpare** [saljam/webwormhole#63]
Guess what website has been pretty handy today as I try to send builds from my macbook to my desktop PC? :)

My flow is:
1 - on macbook load up webwormhole
2 - go to create wormhole
3 - note pasword
4 - go to desktop load up site and connect
5 - go back to laptop drag the files in
6 - go to PC and do things with them.

IF it was possible to cue up + drag files between stages 2->4 it'd save me a round trip to my laptop and back.  Just a thought!

(I understand that that would require an interface change, though, and I don't have any constructive suggestions for how to do it other than maybe add a "queue up files" box that lets you queue up files beside the "new wormhole" button, or maybe beside the QR-Code?)

**Comment by saljam** [comment]
if i understand correctly this is the same as #7? if so yes absolutely!

if we do it for dragged files only, then i think the ui change is tiny. we'd need to make the file list visible and some indicator that they've not been sent yet. maybe a progress bar with no value?

for the file picker dialog, we can also show the button in the "connecting" state and give it a "queue" label.

there's a suggestion in #7 to implicitly create the wormhole on first drag that i also quite like.

**Comment by increpare** [comment]
Ah, yep, that's it exactly 💯

You could do it via a secret interface, yip - that'd cover it for me.  (And if you wanted to go further to create an 'queue up files box' interface element people could click on that'd be something you could do as a later task anyway).

**Comment by increpare** [comment]
(implicitly creating the wormhole on first drag is possibly ok but there is one edge-case where it's confusing - if two novice users wanting to transfer files back-and-forth both accidentally create wormholes. OTOH the vast majority of times I'd guess file transfer is 1-directional, so :) )
