### ISSUE TITLE
cannot find package "github.com/pion/webrtc/v2" in any of:

### ISSUE THREAD

**Issue by mailinglists35** [saljam/webwormhole#67]
````
root@srv:/tmp# go get -u webwormhole.io/cmd/ww
cannot find package "github.com/pion/webrtc/v2" in any of:
        /usr/lib/go-1.15/src/github.com/pion/webrtc/v2 (from $GOROOT)
        /root/go/src/github.com/pion/webrtc/v2 (from $GOPATH)

````

````
root@srv:/tmp# dpkg -l |grep golang
ii  golang                                        2:1.15-1longsleep1+bionic                                                   amd64        Go programming language compiler - metapackage
ii  golang-1.15                                   1.15-1longsleep1+bionic                                                     all          Go programming language compiler - metapackage
ii  golang-1.15-doc                               1.15-1longsleep1+bionic                                                     all          Go programming language - documentation
ii  golang-1.15-go                                1.15-1longsleep1+bionic                                                     amd64        Go programming language compiler, linker, compiled stdlib
ii  golang-1.15-src                               1.15-1longsleep1+bionic                                                     amd64        Go programming language - source files
ii  golang-doc                                    2:1.15-1longsleep1+bionic                                                   all          Go programming language - documentation
ii  golang-docker-credential-helpers              0.5.0-2                                                                     amd64        Use native stores to safeguard Docker credentials
ii  golang-go                                     2:1.15-1longsleep1+bionic                                                   amd64        Go programming language compiler, linker, compiled stdlib
ii  golang-src                                    2:1.15-1longsleep1+bionic                                                   amd64        Go programming language - source files
````

**Comment by mailinglists35** [comment]
Ubuntu 18.04.1 LTS with backported go 1.15

**Comment by mailinglists35** [comment]
oh, I imagined the "go" command would do the git clone as well, turns out you have to first manually git clone this repo, only then run the go command...

**Comment by saljam** [comment]
thanks for reporting. this definitely used to work before. it looks like a go tool GOPATH mode vs modules mode issue.

if it's invoked outside the repo it *does* fetch it. it puts it in $HOME/go, or $GOPATH if that's defined. but now it's running in "GOPATH mode" and it seems like it's unable to find and fetch the pion/webrtc module.

i wonder if a recent go version changed something about the behaviour, or something about how pion/webrtc is tagged changed? i'll look into it. i'm hoping we can do something on our end to make it work again. it's nice to be able to install with one command. and if not we should make the readme clearer.

**Comment by mailinglists35** [comment]
great! I never had go installed on this system and the choices I had were the distro standard 1.10 which I understand it's too old, and a backports repo which had this v 1.15. see also the other new issue I have opened regarding not seeing any ww binary, maybe it's also related to go 1.15?

**Comment by saljam** [comment]
running `go get` outside the source code directory (still!) puts the go tool in gopath mode. the pion module uses a branch for the /v2 version. the go tool in gopath mode is not version aware so it does not fetch the right branch.

luckily, GO111MODULE still works and fixes this:

```
GO111MODULE=on go get webwormhole.io/cmd/ww
```

i've updated the readme to include GO111MODULE.
