### ISSUE TITLE
web: allow queueing files to be sent while still waiting for other side

### ISSUE THREAD

**Issue by saljam** [saljam/webwormhole#7]

**Comment by hantusk** [comment]
+1! UX-wise, dragging a file into the browser before pressing "New wormhole", should automatically create a new wormhole with that file enqueued

**Comment by mytech-today-now** [comment]
This is a really crucial feature.  
It allows for asynchronous data transfers.
The sender needs to create a wormhole, then queue files to send, then transmit the wormhole link to the receiver.  
The sender only needs to keep the wormhole open in a browser window.

**Comment by saljam** [comment]
you can now drag and drop to queue files before the connection is established
