### ISSUE TITLE
Upgrade to pion/webrtc@v3

### ISSUE THREAD

**Issue by Sean-Der** [saljam/webwormhole#77]
Hey @saljam 

I released [v3](https://github.com/pion/webrtc/wiki/Release-WebRTC%40v3.0.0) and would love to help you upgrade. If you want to wait/have any questions happy to answer them.

API wise nothing has changed for you. You already have Trickle ICE enabled and you don't use the Media APIs.

**Comment by saljam** [comment]
awesome, thanks for the ping! i started testing a v3 beta a couple of weeks ago in the branch 's/proxy' (for #69) and it all looked good. i'll bring that up to date and merge it.

**Comment by Sean-Der** [comment]
:fire: if there is anything I can do just tell me and happy to jump in.

Overall been happy with Pion? Anything I can fix/improve? I have a [2021 Goals](https://github.com/pion/webrtc/wiki/Goals-2021) happy to add anything you can think of to it. I think the majority of this list won't get done, unless we get a big wave of contributors :)

**Comment by saljam** [comment]
switched :)

i've been very happy with pion. thanks so much for all you efforts on it!

i would love to see more wasm (even more i'd love to have the time work on that hah) BUT i think this is much more about the state of go's wasm than pion's.

**Comment by Sean-Der** [comment]
That's awesome to hear :) if anything comes up please reach out. Super important to me that the project stays healthy

I haven't done enough WASM stuff. Hopefully demand goes up for it when the performance is way better then alternative AND you can use safer/easier languages.
