### ISSUE TITLE
change the code dictionary

### ISSUE THREAD

**Issue by saljam** [saljam/webwormhole#8]
The current scheme ("slot number"-"dash-separated-words") is a straight clone of magic-wormhole's. It's pretty good and I like it, but I'm wondering if there are other variations we can explore.

One idea: PGP word list has parity information, so we could also encode the slot number as words with reversed parity. Where the parity changes we know it's the split between the slot and the secret.

Any other thoughts?

**Comment by hantusk** [comment]
UX-wise, it would be good if the scheme supports adding in hyphens/word separators automatically, and they are tedious to write on mobile (e.g. by restricting the word-dictionary to only having the longest form of a given character sequence)

**Comment by dncohen** [comment]
The current scheme is brief, which is great.

It mixes numbers and words, which makes it hard to relay by voice.

It would be nice to have a choice (3 or more) words, or 6 digits like the OTPs that users are used to for 2FA.

**Comment by saljam** [comment]
I like the idea of giving having the choice of how the code is encoded!

Assuming we encode the slot as a word. 3 words == 3 bytes which can be spelled in ~9 decimal digits, but mostly ~7 since the signalling server tries to allocate slots with as few digits as possible.

So, one thing we can do is use the bytes instead of the words as the actual PAKE password, and leave the word encoding to the presentation layer. This means we can switch up how the code is displayed, as numbers, as English pgpwords, or as localised words in other languages.

Re: rotating codes. We deal with the brute-force risk of it being such a short passwords (by default only 2-bytes!) by giving the B side a single guess only, so in effect they rotate on first fail. This is the magic-wormhole approach and it works pretty well. Not rotating the codes is also convenient if both machines are not accessible at the same time. Using magic-wormhole I've run `wormhole send` on a machine, drove home, then ran `wormhole receive` successfully and it would be nice to preserve this usecase.

That said, I'm happy to try adding an option for auto-rotating codes and see what that feels like! There might be a use for it that I can't currently imagine.

Also definitely +1 on the length option. The command line client already has that, i just didn't get around to making UI for it in the web interface.

**Comment by dncohen** [comment]
I didn't realize about rotating the slot on first fail.  That's good to know, and clever.

Thinking out loud, and at the risk of over-engineering... Say that a server is configured for 16 slots (4 bits).  The A-side could calculate 2 bytes of magic code, and 4 bits of checksum. So 4 bits (slot) plus 2 bytes (code) plus 4 bits (checksum) fits in three words.

On the B-side, the checksum is validated client-side.  So a well behaved client can avoid reset on typo (1 out of every 16 typos the checksum would fail, in this 4-bit example).  If the client is using words, typos may be a non-issue, but if digits a checksum is nice to have.

A higher traffic server could configure more slots, and either choose a less effective checksum or longer password.

**Comment by saljam** [comment]
aside: the more i used this the less impressed i am by the choices in the pgp word list. some combinations are rather unsavoury and we ought to find a replacement for this dictionary.

**Comment by oridb** [comment]
It seems like taking the scrabble dictionary would be a good start -- should be fairly tame, and have a lot of entropy.

**Comment by oridb** [comment]
...Scratch that, I should have looked at the scrabble word list. Far too many obscure words where people will just go "what did you say?"

**Comment by saljam** [comment]
some more thoughts:

- [proquints](https://arxiv.org/html/0901.4016).
pro: short, designed with phonetics in mind.
con: sounds like gibberish. is that a con?

- someone pointed out this [wordlist](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md) to me
pro: multiple languages
con: a lot of words sound similar (boring, borrow, boss, box, absorb, absurd, etc.)

- generate our own
pro: probably a fun project
con: will take a while

**Comment by dncohen** [comment]
I was going to make a similar comment...

Proquints I came across because upspin uses them.  I think it is a con that they sound like gibberish.  I like the idea of speaking a code over the phone without having to spell everything out. 

And bip39 is popular.  I think the multiple languages is compelling.

**Comment by tyehle** [comment]
What about one of EFF’s dice ware wordlists?
https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases

**Comment by saljam** [comment]
@nickzoic has a word list and a nice write-up of generating it using soundex: https://nick.zoic.org/art/shorter-words-list/

**Comment by nickzoic** [comment]
Hi @saljam!  Yeah, I was messing around with a similar idea and thought it might make a useful contribution.
A large decimal number split into groups is hard to beat though and works in any language!

**Comment by saljam** [comment]
i just pushed the following changes:
- replace the pgp word list with nick's word list.
- change the magic-wormhole format of <slot number>-<secret words> to a single list of words, with the slot encoded as a [uvarint](https://golang.org/pkg/encoding/binary/#PutVarint) at the beginning.

that is, instead of codes looking like `5-python-bottomless` they now look like `debug-potato-indoors`

it's available on https://tip.webwormhole.io/

i realise this is very bikesheddable but i'd still appreciate feedback either change before deploying to the main website and publishing the web extension.

**Comment by saljam** [comment]
i like the new word list, but i'm in two minds about dropping the number.

arguments for dropping it:
- we get 128 single-word slots instead of 10
- it wasn't clear why it's there anyway for a lot of people i asked
- avoids confusion with magic-wormhole codes

arguments for keeping it:
- when explaining how this works it's easier to point out that the signalling server sees the number but not the secret words.
- maybe easier to match with regexp with fewer false positives?

i'll drop the number for now and see how it goes. if it turns out to be a mistake we can always bring it back and bump the protocol version to prompt folks to upgrade their clients.
