### ISSUE TITLE
Feature request: Support for sending text

### ISSUE THREAD

**Issue by rene-dev** [saljam/webwormhole#83]
I tried to send a long link to another device, but pasting text does not seem to work. I think this would be a very useful feature.

**Comment by saljam** [comment]
Hi!

Did you try it on the browser extension or on the website? I recently added support for pasting with cmd+v/ctrl+v on the web version. I'll make an extension release this week that'll also bring this functionality.

(The UX definitely needs some work though! It's not discoverable and doesn't work on mobile or touch screen. [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) looks promising to add a "paste" button but different browsers implemented it differently last time I tried it.)

**Comment by saljam** [comment]
I've added a button that uses the Clipboard API on browsers that support it. It seems to work on Chrome, Safari (macOS & iOS) but Firefox sadly doesn't. cmd+v/ctl+v should still work on desktop browsers and the extensions that support it.

I'll close this. Feel free to reopen if you spot anything broken in it.
