### ISSUE TITLE
Error when adding turn server

### ISSUE THREAD

**Issue by iamdoubz** [saljam/webwormhole#84]
So I've edited `server.go` to point to my turn server (yes, it is coturn), let us say it is using the url of turn.dev running on port 3478. How, exactly, would I do that? I have tried `set.StringVar(&turnServer, "turn", "turn:turn.dev:3478", "TURN server to use for relaying")` and also `set.StringVar(&turnServer, "turn", "turn.dev:3478", "TURN server to use for relaying")`. Yes, I have filled in the turn secret as well and I also do know that the turn server works as I use it for Nextcloud Talk flawlessly.

Now, the console log I get in my browser:

- service worker registered: activated (main.js:640)
- requesting slot (webwormhole.js:53)
- websocket session established (webwormhole.js:247)
- assigned slot: 5 (webwormhole.js:84)
- Uncaught TypeError: Failed to construct 'RTCPeerConnection': Malformed RTCIceServer
    at Wormhole.newPeerConnection (webwormhole.js:233)
    at Wormhole.onmessage (webwormhole.js:90)
    at WebSocket.ws.onmessage (webwormhole.js:70)

What am I doing wrong?

Extra info: using nginx as the reverse proxier.

Thanks for an awesome piece of software. I really like it for sending large files securely ever since Firefox Send went down.

**Comment by saljam** [comment]
hm, i can't reproduce this. did you make any other changes to server.go?

try with using the flags instead of editing the source code: `ww server -turn=turn:turn.dev:3478 -turn-secret=foo`

**Comment by iamdoubz** [comment]
Should have typed `./ww server -help` before opening a ticket... ugh. Thank you very much, my server is up and running!

So, I do want to point out one thing: when I run the command above, it has `-ui` as a default of "../../web", but in the source code, it is `./web`. If I do not change source code, I get 404's. If I pass the `-ui=../../web`, I get CSP errors and nothings loads. Just my observation is all.

And now I have a separate question, how do I pass multiple stun/turn servers? I think I would keep using `-stun=` for each of the stun servers, but how would I do the turn servers? Do the secrets have to all be the same?

**Comment by saljam** [comment]
glad you got it working.

not really sure why you got csp errors for using `-ui=../../web`. works for me if i'm in the `cmd/ww` directory. i usually invoke the server from the git root directory hence `./web`

for stun give the `-stun` argument multiple urls separated by commas. for turn, it only supports one.

**Comment by iamdoubz** [comment]
Running from root git dir makes sense. I am running it from `cmd/ww` and didn't see why it did not want to work.

Anyway, everything is working flawlessly. Now, time to do a, oh idk, 1GB test because reasons.

Thank you again for all your help and insight.
