### ISSUE TITLE
webwormhole.js:19 Uncaught (in promise) bad code

### ISSUE THREAD

**Issue by mfbx9da4** [saljam/webwormhole#85]
Looks like this line is failing to decode the passcode 

```
[this.slot, this.pass] = webwormhole.decode(code);
```

https://github.com/saljam/webwormhole/blob/master/web/webwormhole.js#L44

```
webwormhole.js:19 Uncaught (in promise) bad code
(anonymous) @ webwormhole.js:19
(anonymous) @ webwormhole.js:18
Wormhole @ webwormhole.js:17
connect @ main.js:375
```

Chrome version 89

**Comment by saljam** [comment]
hi david

sounds like the passcode it was given is not a valid one, i.e. uses words not in its dictionary. a typo would trigger this.

was it a code you expected to parse correctly? was there any unusual punctuation or whitespace that we can clean up?

**Comment by mfbx9da4** [comment]
Hey there 👋 

I realize now this was a dumb user error. I didn't read the placeholder and assumed I was meant to provide the passcode, especially as it is auto-focused.

![image](https://user-images.githubusercontent.com/1690659/115241834-290e7600-a119-11eb-8db8-19772f67dd7a.png)

I entered "asdf". A user error would have helped me something like "The passcode you entered was not generated by web wormhole. Please enter a valid passcode."

Alternatively two call to actions, primary "New wormhole", secondary "Join wormhole" which would reveal the input.


--- 

Side note 

RE `// It is very possible that I do not understand how to us promises "correctly".` You're definitely using them correctly but I do prefer this pattern.

```ts
const createDeferredPromise = <T>() => {
  let resolve: (value: T) => void = () => {}
  let reject: (value: T) => void = () => {}
  const promise = new Promise<T>((res, rej) => {
    resolve = (value: T) => res(value)
    reject = (value: T) => rej(value)
  })
  return { promise, resolve, reject }
}

this.phase1 = createDeferredPromise()
this.phase2 = createDeferredPromise()
this.phase3 = createDeferredPromise()
```

**Comment by saljam** [comment]
i admit the wording is almost unhelpfully laconic. the whole interface needs another round of review.

thanks for the promise function tip. all this to manage the webrtc api's state machine is kind of absurd. this must be the source of so many bugs out there.

**Comment by mfbx9da4** [comment]
> RE I'd welcome a clearer or more idiomatic approach in JS if someone were to suggest one.

I haven't run this code so take it with a pinch of salt but the basic idea is to use async/await to make it more idiomatic. I think it's nicer but might not take your fancy.

```ts
const createWebSocketClient = (url) => {
  const ws = new WebSocket(url);
  const listenersByType = new Map();

  const addListener = (type, callback) => {
    if (!listenersByType.get(type)) listenersByType.set(type, new Set());
    const listeners = listenersByType.get(type);
    listeners.add(callback);
  };

  const removeListener = (type, callback) => {
    const listeners = listenersByType.get(type);
    listeners.delete(callback);
  };

  ws.onmessage = (rawMessage) => {
    const message = JSON.parse(rawMessage.data);
    const listeners = listenersByType.get(type);
    for (const l of listeners.values) l(message);
  };

  const wait = async (type, timeout = 5000) => {
    return new Promise((resolve, reject) => {
      const listener = (message) => {
        resolve(message);
        removeListener(listener);
      };
      addListener(listener);
      setTimeout(() => {
        reject(new Error(`TimeoutError: Waiting for ${type}`));
        removeListener(listener);
      }, timeout);
    });
  };

  return { ws, wait };
};

const url = Wormhole.wsserver("https://webwormhole.io/", this.slot);
const client = createWebSocketClient(url, this.protocol);
// ... can setup client.ws.onopen, client.ws.onerror as before

// note the JSON should come out parsed
const { slot, iceServers } = await client.wait("slot");
const pc = peerConnection(iceServers);
this.phase1.resolve({ code, pc });
client.ws.send({ foo: "bar" });
const pake_a = await client.wait("pake_a");
client.ws.send({ baz: "asdf" });
const answer = await client.wait("answer");
```


RE Design I quite like this way of showing optionality with two call to actions

![image](https://user-images.githubusercontent.com/1690659/115443646-69e6b780-a20b-11eb-8c9d-b505ac364452.png)


RE parseInt

Though on modern browsers you'll probably be alright, it would help me sleep tonight if you did

```
this.slot = parseInt(msg.slot, 10);
```

as you could end up with `parseInt("08") -> 0`

https://github.com/saljam/webwormhole/blob/master/web/webwormhole.js#L85

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#octal_interpretations_with_no_radix

**Comment by saljam** [comment]
thanks!

i'll have a closer look at your `wait` function and maybe try something like that. ideally, though, this signalling code should all be in go. it's not at the moment because of the resulting wasm's file size and (old?) limitations in the webrtc library. see #59. it's been almost a year since i tried that, so it's worth revisiting.

i just added a radix to parseInt and switched to isSafeInteger. i think it's fairly safe the way it was - the string we give to parseInt is not a user input, and parseInt by definition should always either return a number or a NaN, but it's good to be paranoid.

**Comment by mfbx9da4** [comment]
Let me give it a go! Would be great to get a contribution commit!

**Comment by mfbx9da4** [comment]
Started a PR, but in draft state as it's very much a work in progress. Only spent 25 mins or so. Left a few `TODO: ` questions if you have a moment to answer. Otherwise, no worries, will ping when there is something more to look at.

https://github.com/saljam/webwormhole/pull/86/files

**Comment by mfbx9da4** [comment]
https://github.com/saljam/webwormhole/pull/87 Added second PR wrt UI feedback above. It's just a suggestion at this point.
