### ISSUE TITLE
files are not downloading on Firefox

### ISSUE THREAD

**Issue by bbigras** [saljam/webwormhole#89]
It's working with Chrome.

I'll try again without addons.

I see this but the download doesn't start. No error in the js console.
![image](https://user-images.githubusercontent.com/24027/117052232-037f9000-ad07-11eb-9fe3-320da53faab3.png)

EDIT: it works with a fresh firefox profile so the problem is probably an addon or my privacy settings.

**Comment by bbigras** [comment]
I fixed the problem by clearing my cache.

**Comment by saljam** [comment]
i was just about to suggest that! a "hard refresh" should also fix it in browsers that still allow that.

last release made some html and js refactoring and clearly my cache control headers weren't up to scratch. fix for that on its way.
