### ISSUE TITLE
Regression: browser checks broken when navigator.clipboard is missing

### ISSUE THREAD

**Issue by richfelker** [saljam/webwormhole#90]
I found today that webwormhole no longer works; it hangs on loading. Pulling up the web console in Firefox showed:

```
Content Security Policy: The page’s settings blocked the loading of a resource at data: (“default-src”).
quirks: no serviceworkers
```

Suggesting this might be the reason. I disable serviceworkers because I don't want random sites running background code after I leave them. Is this a hard dependency now or could it be fixed? Or is the problem likely something different?

**Comment by richfelker** [comment]
I missed that it also showed:

```
Uncaught (in promise) TypeError: navigator.clipboard is undefined
```

This is because I disable the clipboard API for privacy and security reasons.

**Comment by saljam** [comment]
Thanks for the report! Both of these are optional. (The service worker is only to trick the browser's download dialog into streaming data from WebRTC. Helps with large files.)

I think my check for the clipboard API isn't up to scratch. I'll send a fix for that in a minute.

	// Firefox does not support clipboard.read.
	if (!navigator.clipboard.read) {
		hacks.noclipboardapi = true;
		console.log("quirks: clipboard api not supported");
	}

**Comment by saljam** [comment]
I think dcb26cd should handle this. This is already running on https://tip.webwormhole.io. Let me know that does or doesn't fix it for your setup!

**Comment by saljam** [comment]
Aside: which browser do you use, and how did you disable the clipboard API?

I'm trying to wrap my head around WebDriver to add browser integration tests and it would be good to include this.

**Comment by richfelker** [comment]
I think it's `dom.event.clipboardevents.enabled` in `about:config` (Firefox).

**Comment by richfelker** [comment]
And yes, it's fixed on tip. Thanks!

**Comment by saljam** [comment]
Thanks for confirming. I'm pushing it to the main site now.

> I think it's `dom.event.clipboardevents.enabled` in `about:config` (Firefox).

I tried that on Firefox 88 at first, but it only removed `navigator.clipboard.readText`. I think some provacy extensions might remove the whole object. I've seen some that do that for WebRTC. It's always fun on the Web!
