### ISSUE TITLE
scrollbars visible on edge browser

### ISSUE THREAD

**Issue by increpare** [saljam/webwormhole#94]
![image](https://user-images.githubusercontent.com/465632/119465828-55cf3200-bd44-11eb-96a7-f83c7ea1d0dc.png)

on Version 90.0.818.66 (Offizielles Build) (64-Bit) on Windows 10 Pro

In CSS, setting     

```
overflow-y: auto;
overflow-x: auto;
```

to the container with id main fixes it (And should still show them if necessary)

**Comment by saljam** [comment]
oof i ought to make my browser always show these. thanks!
